//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UMusic.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_genre
    {
        public tb_genre()
        {
            this.tb_album = new HashSet<tb_album>();
        }
    
        public int genreId { get; set; }
        public string genreName { get; set; }
    
        public virtual ICollection<tb_album> tb_album { get; set; }
    }
}
