//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UMusic.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_local
    {
        public tb_local()
        {
            this.tb_album = new HashSet<tb_album>();
            this.tb_artist = new HashSet<tb_artist>();
        }
    
        public int localId { get; set; }
        public string localName { get; set; }
    
        public virtual ICollection<tb_album> tb_album { get; set; }
        public virtual ICollection<tb_artist> tb_artist { get; set; }
    }
}
