//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UMusic.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class tb_order
    {
        public tb_order()
        {
            this.tb_orderDetails = new HashSet<tb_orderDetails>();
        }
    
        public int orderId { get; set; }
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}")]
        public System.DateTime orderdate { get; set; }
        public string orderStatus { get; set; }
       [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}")]
        public System.DateTime createDate { get; set; }
        public double total { get; set; }
        public int userid { get; set; }
    
        public virtual ICollection<tb_orderDetails> tb_orderDetails { get; set; }
        public virtual tb_user tb_user { get; set; }
    }
}
