//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UMusic.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_singleSong
    {
        public int songId { get; set; }
        public int albumId { get; set; }
        public string songName { get; set; }
        public string duration { get; set; }
    
        public virtual tb_album tb_album { get; set; }
    }
}
