//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UMusic.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class view_collection
    {
        public string albumname { get; set; }
        public int albumid { get; set; }
        public string imagesurl { get; set; }
        public int artistid { get; set; }
        public string artistname { get; set; }
        public int userid { get; set; }
    }
}
