//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UMusic.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class view_OrderItem
    {
        public int albumid { get; set; }
        public string imagesUrl { get; set; }
        public string albumname { get; set; }
        public string artistName { get; set; }
        public string genreName { get; set; }
        public int OrderID { get; set; }
        public int quantity { get; set; }
        public double unitprice { get; set; }
        public System.DateTime orderdate { get; set; }
    }
}
