//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UMusic.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_artist
    {
        public tb_artist()
        {
            this.tb_album = new HashSet<tb_album>();
        }
    
        public int artistId { get; set; }
        public string artistName { get; set; }
        public string imageUrl { get; set; }
        public string decription { get; set; }
        public int localId { get; set; }
    
        public virtual ICollection<tb_album> tb_album { get; set; }
        public virtual tb_local tb_local { get; set; }
    }
}
