//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UMusic.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_cart
    {
        public tb_cart()
        {
            this.tb_cartDetails = new HashSet<tb_cartDetails>();
        }
    
        public int cartId { get; set; }
        public int userId { get; set; }
    
        public virtual tb_user tb_user { get; set; }
        public virtual ICollection<tb_cartDetails> tb_cartDetails { get; set; }
    }
}
