//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UMusic.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class view_cartItem
    {
        public string albumName { get; set; }
        public string artistName { get; set; }
        public int leftNum { get; set; }
        public int quantity { get; set; }
        public string imagesUrl { get; set; }
        public string genreName { get; set; }
        public double price { get; set; }
        public int albumid { get; set; }
        public int cartid { get; set; }
    }
}
